export enum MutationTypes {
    SET_IS_FETCHING_GISTS = 'SET_IS_FETCHING_GISTS',
    SET_GISTS = 'SET_GISTS',
    SET_GISTS_COLLECTION = 'SET_GISTS_COLLECTION',
    SET_FILTER_TIME_MINUTES = 'SET_FILTER_TIME_MINUTES'
}
